/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author DELL
 */
public class SplashForm extends javax.swing.JFrame {

    /**
     * Creates new form SplashForm
     */
    public SplashForm() {
        initComponents();
        Date();
        Time();
    }
    
    public void Date(){
        DateTimeFormatter dtf=DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDateTime now=LocalDateTime.now();
        Date.setText(dtf.format(now));
    
    }
    
    public void Time(){
        DateTimeFormatter dtf=DateTimeFormatter.ofPattern("HH:mm:ss");
        LocalDateTime now=LocalDateTime.now();
        Time.setText(dtf.format(now));
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();
        label1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LoadingText = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(15, 15, 15));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SYSTEM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 600, 60));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("GROCERY MANAGEMENT");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 600, 60));

        ProgressBar.setBackground(new java.awt.Color(255, 255, 255));
        ProgressBar.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(ProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 550, 20));

        label1.setBackground(new java.awt.Color(204, 204, 204));
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("100%");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, -1, -1));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("WELCOME");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 600, 60));

        LoadingText.setForeground(new java.awt.Color(255, 255, 255));
        LoadingText.setText("LoadingText");
        jPanel1.add(LoadingText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        Date.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Date.setForeground(new java.awt.Color(255, 255, 255));
        Date.setText("Date");
        jPanel1.add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        Time.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Time.setForeground(new java.awt.Color(255, 255, 255));
        Time.setText("Time");
        jPanel1.add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/background.jpg"))); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setPreferredSize(new java.awt.Dimension(580, 380));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 590, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
       SplashForm SplashScreen=new SplashForm();
        SplashScreen.setVisible(true);
        
           
        try {
                for (int i=0;i<=100;i++)
                {
                    Thread.sleep(50);
                    SplashScreen.label1.setText(Integer.toString(i)+"%");
                    SplashScreen.ProgressBar.setValue(i);
                    
                    if (i==0){
                        SplashScreen.LoadingText.setText("Starting On Module...");
                    }
                    
                    if (i==10){
                        SplashScreen.LoadingText.setText("Turning On Module...");
                    }
                    
                    if (i==20){
                        SplashScreen.LoadingText.setText("Loading Module...");
                    }
                    
                    if (i==50){
                        SplashScreen.LoadingText.setText("Connecting To Database...");
                    }
                    
                    if (i==70){
                        SplashScreen.LoadingText.setText("Connecting Sucssesfuly!");
                    }
                    if (i==80){
                        SplashScreen.LoadingText.setText("Launching Application...");
                    }
                                    
                    if(i==100)
                    {
                        SplashScreen.LoadingText.setText("Launch...");
                        //SplashScreen.dispose();
                        SplashScreen.dispose();
                        new LoginForm().setVisible(true);
                        
                        //new HomeForm().setVisible(true);
                        //LoginForm loginformopen=new LoginForm();
                        //loginformopen.setVisible(true);
                    }
                }
               
            }
        catch(Exception e) 
            {
                
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date;
    private javax.swing.JLabel LoadingText;
    public javax.swing.JProgressBar ProgressBar;
    private javax.swing.JLabel Time;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel label1;
    // End of variables declaration//GEN-END:variables
}
